import {
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER,
  TWILIO_BASEURL,
  TWILIO_AUTHORIZATION
} from 'react-native-dotenv'

module.exports = {
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER,
  TWILIO_BASEURL,
  TWILIO_AUTHORIZATION
}
